steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/data-management-img', '.']
    id: 'Build Docker image'
    timeout: 30m

  # Paso 2: Empujar la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/data-management-img']
    id: 'Push Docker image'
    timeout: 10m

  # Paso 3: Desplegar la imagen a Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-service'  # Nombre del servicio en Cloud Run
      - '--image'
      - 'gcr.io/$PROJECT_ID/data-management-img'
      - '--region'
      - 'us-central1'  # Cambia la región según tus necesidades
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # O usa '--no-allow-unauthenticated' para requerir autenticación
    id: 'Deploy to Cloud Run'
    timeout: 10m

images:
  - 'gcr.io/$PROJECT_ID/data-management-img'

options:
  logging: CLOUD_LOGGING_ONLY
